In [13]:
df["Price range"].mode()

0    1
Name: Price range, dtype: int64

In [14]:
df[["Price range", "Aggregate rating"]].groupby(by="Price range").mean().reset_index().rename(columns={"Aggregate rating": "Average Rating"})

   Price range  Average Rating
0            1        1.999887
1            2        2.941054
2            3        3.683381
3            4        3.817918

In [15]:
rating_df = df[["Price range", "Aggregate rating", "Rating color"]]

In [16]:
df["Rating color"].unique()

array(['Dark Green', 'Green', 'Yellow', 'Orange', 'White', 'Red'],
      dtype=object)

In [17]:
average_ratings = rating_df.groupby("Price range")["Aggregate rating"].mean().reset_index()
average_ratings

   Price range  Aggregate rating
0            1          1.999887
1            2          2.941054
2            3          3.683381
3            4          3.817918

In [18]:
result = pd.merge(average_ratings, rating_df[["Price range", "Rating color"]].drop_duplicates(), on="Price range")
result

    Price range  Aggregate rating Rating color
0             1          1.999887       Yellow
1             1          1.999887        White
2             1          1.999887       Orange
3             1          1.999887   Dark Green
4             1          1.999887        Green
5             1          1.999887          Red
6             2          2.941054   Dark Green
7             2          2.941054       Orange
8             2          2.941054       Yellow
9             2          2.941054        Green
10            2          2.941054        White
11            2          2.941054          Red
12            3          3.683381   Dark Green
13            3          3.683381        Green
14            3          3.683381       Yellow
15            3          3.683381       Orange
16            3          3.683381        White
17            3          3.683381          Red
18            4          3.817918        Green
19            4          3.817918   Dark Green
20            4          3.817918       Yellow
21            4          3.817918       Orange
22            4          3.817918        White
23            4          3.817918          Red

In [19]:
highest_avg_rating = result.loc[result["Aggregate rating"].idxmax()]
highest_avg_rating

Price range                4
Aggregate rating    3.817918
Rating color           Green
Name: 18, dtype: object